use serde::{Deserialize, Serialize};

/// Granular metric tracking for LLM tokens, latency, and estimated cost.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SpanMetrics {
    /// Number of prompt tokens sent to the model.
    pub input_tokens: Option<u32>,
    /// Number of completion tokens generated by the model.
    pub output_tokens: Option<u32>,
    /// Total tokens (computed or provider-reported).
    pub total_tokens: Option<u32>,
    /// Number of context-cached prompt tokens.
    pub cached_tokens: Option<u32>,
    /// Number of internal reasoning tokens (e.g. OpenAI o1/o3 architectures).
    pub reasoning_tokens: Option<u32>,
    /// Pre-computed or dynamically enriched financial cost in US Dollars.
    pub estimated_cost_usd: Option<f64>,
}

impl SpanMetrics {
    /// Constructs an empty metrics container.
    pub const fn new() -> Self {
        Self {
            input_tokens: None,
            output_tokens: None,
            total_tokens: None,
            cached_tokens: None,
            reasoning_tokens: None,
            estimated_cost_usd: None,
        }
    }

    /// Builder helper to set input and output token counts, auto-computing total.
    pub fn with_tokens(mut self, input: u32, output: u32) -> Self {
        self.input_tokens = Some(input);
        self.output_tokens = Some(output);
        self.total_tokens = Some(input.saturating_add(output));
        self
    }

    /// Builder helper to set estimated USD cost.
    pub fn with_cost(mut self, cost_usd: f64) -> Self {
        self.estimated_cost_usd = Some(cost_usd);
        self
    }

    /// Builder helper to set cached tokens.
    pub fn with_cached_tokens(mut self, cached: u32) -> Self {
        self.cached_tokens = Some(cached);
        self
    }

    /// Builder helper to set reasoning tokens.
    pub fn with_reasoning_tokens(mut self, reasoning: u32) -> Self {
        self.reasoning_tokens = Some(reasoning);
        self
    }

    /// Ensures `total_tokens` is populated if `input_tokens` and `output_tokens` are present.
    pub fn normalize_totals(&mut self) {
        if self.total_tokens.is_none() {
            if let (Some(inp), Some(out)) = (self.input_tokens, self.output_tokens) {
                self.total_tokens = Some(inp.saturating_add(out));
            }
        }
    }
}
